---
title: "ML-Assigment-3 Naive bayes"
author: "Harish Kunaparaju"
date: "2022-10-13"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(pivottabler)
library(caret)
library(ISLR)
library(dplyr)
library(e1071)

```


```{r}
#Importing data set for current enviroment.
library(readr)
data <- read.csv("UniversalBank.csv")
str(data)
```


```{r}
# converting Online,Credit Card,Personal loan,to factors from int.
data$Online<-as.factor(data$Online)
is.factor(data$Online)
data$CreditCard<-as.factor(data$CreditCard)
is.factor(data$CreditCard)
data$Personal.Loan<-as.factor(data$Personal.Loan)
is.factor(data$Personal.Loan)
str(data)
```


```{r}
#partition the data into Training (60%) and validate (40%).
set.seed(123)
Train_index<- createDataPartition(data$Personal.Loan, p=0.60, list = FALSE)
traning <- data[Train_index,]
validation<-data[-Train_index,]  
```


```{r}
#Data Normalization.
Mydata <- preProcess(data[,-c(10,13,14)], method = c("center", "scale"))
Feature_tdata <- predict(Mydata, traning)
Feature_vdata <- predict(Mydata, validation)
```


```{r}
#A. Creating Pivot Table with Online as column variable and CC, Personal.Loan as row variables by using Ftable function.
pivot_data<- ftable(Feature_tdata$Personal.Loan, Feature_tdata$Online, Feature_tdata$CreditCard, dnn=c('Personal.loan','CreditCard', 'Online'))
pivot_data
#B.Probability of Loan Acceptance (Loan=1) conditional on CC=1 and Online=1.
prob_data<-pivot_data[4,2]/(pivot_data[2,2]+pivot_data[4,2])
prob_data
```

```{r}
# Creating two separate Pivot tables for the training data.
#C1.probability for personal loan and Online.
pivot_data<- ftable(Feature_tdata$Personal.Loan,Feature_tdata$Online,dnn=c('Personal.loan','Online'))
pivot_data
#C2.probability for personal loan and Credit Card.
pivot_data2<- ftable(Feature_tdata$Personal.Loan,Feature_tdata$CreditCard, dnn=c('Personal.loan','CreditCard'))
pivot_data2
```

```{r}
#D.(i).P(CC=1 | Loan= 1)(The proporation of credit card holders among the loan acceptors)
data1<- pivot_data2[2,2]/(pivot_data2[2,2]+pivot_data2[2,1])
data1
```

```{r}
#D.(ii).P(Online=1 | Loan=1)
data2 <- pivot_data[2,2]/(pivot_data[2,2]+pivot_data[2,1])
data2
```

```{r}
#D.(iii).P(Loan=1)(The proporation of loan acceptors)
data3 <- ftable(Feature_tdata[,10])
data3
data3 <- data3[1,2]/(data3[1,2]+data3[1,1])
data3
```

```{r}
#D.(iv).P(CC=1 | Loan=0)
data4 <- pivot_data2[1,2]/(pivot_data2[1,2]+pivot_data2[1,1])
data4
```
```{r}
#D.(v).P(Online=1 | Loan=0)
data5 <- pivot_data[1,2]/(pivot_data[1,2]+pivot_data[1,1])
data5
```
```{r}
#D.(vi).P(Loan=0)
data6 <- ftable(Feature_tdata[,10])
data6
data6 <- data6[1,1]/(data6[1,1]+data6[1,2])
data6
```

```{r}
#E.Computing Naive Bayes using conditional probabilities from D [P(Loan=1/Creditcard=1,Online=1)].
nb <- (data1*data2*data3)/(data1*data2*data3+data4*data5*data6)
nb
```


#F.Compare E values with one obtained from the pivot table in B,Whih is more Accurate estimate.

The probability derived from Bayes probability i.e., B. is 0.0984556 and the probability derived from Naive's Bayes i.e., is 0.1000. The comparison between Bayes and Naive bayes shows that Naive Bayes has a higher probability.



```{r}
#G.Using Naive Bayes directly applied to the data.
nb_model <-naiveBayes(Personal.Loan~Online+CreditCard, data=Feature_tdata)
nb_model

#From the below table we can observe that for P(Loan=1| CC=1, Online=1), following values are to be considered - 0.096(Loan = 1), 0.6111(Online=1), 0.2916(CC=1). The values derived from the table to calculate Naive Bayes will be same as the value derived in E for calculating Naive Bayes but was calculated from Bayes probability.
```



